#!/usr/bin/env python3
"""Lay out a HyperFrames project from a locked video spec.

Reads video-spec.json, derives the build sheet with spec.py, and writes a
project structure that follows the framework's own conventions: every scene a
sub-composition, one caption track, one element kind per track, hosts that carry
timing and nothing else. Each scene file is pre-cut into the arrival slots its
pacing implies, so a scene cannot silently ship as one frozen block.

  python3 scripts/scaffold.py video-spec.json --project <dir>
  python3 scripts/scaffold.py video-spec.json --project <dir> --dry-run

Run `npx hyperframes init <dir>` first — init owns hyperframes.json, meta.json
and package.json, and this script never touches them.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPTS))

from spec import PACING, TONES, norm_role, validate  # noqa: E402

EASE = {
    "calm": "power1.inOut", "energetic": "back.out(1.7)", "serious": "power2.out",
    "funny": "elastic.out(1, 0.5)", "emotional": "sine.inOut", "mysterious": "power1.in",
    "inspirational": "power3.out",
}

# A promised travel is only measurable if the subject is opaque in both frames
# being compared, so a directional arrival ramps its opacity over the first third
# of the window and spends the rest of it actually moving. Offset is where the
# subject STARTS, relative to its rest position: travelling right means starting left.
OFFSET = {
    "right": (-160, 0), "left": (160, 0), "top": (0, 160), "bottom": (0, -160),
    "top-right": (-160, 160), "top-left": (160, 160),
    "bottom-right": (-160, -160), "bottom-left": (160, -160),
}

ASSET_DIRS = ("media", "icons", "logos", "fonts", "audio")

GITIGNORE = """# generated by hyperframes — never hand-edit
snapshots/
renders/
.hyperframes/
beats/
node_modules/
"""

SCENE_TEMPLATE = """<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
  </head>
  <body>
    <template>
      <!--
        scene {index} · {role} · {start}–{end} ({seconds:.1f}s)
        intent   {intent}
        content  {content}
        arrivals {beats} at {pacing} pacing ({shot_lo:.1f}–{shot_hi:.1f}s per arrival)
        shape    {blueprints}
        motion   {motion}
        easing   {ease} ({tone})

        Read {blueprint_doc}before animating. Do not tween a .clip node itself —
        the framework owns clip visibility; animate the inner <span>.
      -->
      <style>
        #root {{
          position: absolute;
          inset: 0;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          gap: 40px;
          color: #f4f4f5;
          font-family: Inter, ui-sans-serif, system-ui, sans-serif;
        }}
        .beat {{
          position: absolute;
          inset: 10% 10% 10% 10%;
          display: flex;
          align-items: center;
          justify-content: center;
        }}
        .beat span {{
          font-size: {font_size}px;
          font-weight: {font_weight};
          letter-spacing: -0.03em;
          line-height: 1.05;
          text-align: center;
          max-width: 80%;
        }}
      </style>

      <div id="root" data-composition-id="{cid}" data-width="{width}" data-height="{height}">
{beats_markup}
      </div>

      <script>
        const tl = gsap.timeline({{ paused: true }});
{beats_tweens}
        window.__timelines["{cid}"] = tl;
        tl.seek(0);
      </script>
    </template>
  </body>
</html>
"""

BEAT_MARKUP = """        <div class="beat clip" id="{bid}" data-start="{start}" data-duration="{duration}" data-track-index="{track}">
          <span>[beat {n} — {hint}]</span>
        </div>"""

DECORATION_FILE = """<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
  </head>
  <body>
    <template>
      <!--
        The decoration layer: one host on the timeline, spanning the whole film,
        holding every ambient treatment (grain, vignette, glow, tint, hairlines).
        Keep it non-interactive and behind the scenes: CSS for layering, and the
        track index below every scene host.

        Idle motion here must be FINITE — hyperframes-animation bans repeat:-1.
        Use sine-wave-loop's bounded-repeats form, and give any pulsing element
        peak clearance so it never clips the frame edge.
      -->
      <style>
        #root {{
          position: absolute;
          inset: 0;
          pointer-events: none;
        }}
        #decorations-vignette {{
          position: absolute;
          inset: 0;
          opacity: 0;
          background: radial-gradient(ellipse at center, transparent 55%, rgba(0, 0, 0, 0.55) 100%);
        }}
      </style>

      <div id="root" data-composition-id="{cid}" data-width="{width}" data-height="{height}">
        <div id="decorations-vignette"></div>
      </div>

      <script>
        const tl = gsap.timeline({{ paused: true }});
        tl.fromTo("#decorations-vignette", {{ opacity: 0 }},
          {{ opacity: 1, duration: {fade:.2f}, ease: "{ease}" }}, 0);
        window.__timelines["{cid}"] = tl;
        tl.seek(0);
      </script>
    </template>
  </body>
</html>
"""

CAPTIONS_FILE = """<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
  </head>
  <body>
    <template>
      <!--
        The single caption track. Every caption group lives in THIS file, in
        order — one row in Studio, not one row per group. Keep caption text
        inside the title-safe box (80% of the frame, 10% inset on every edge).
        Word timing and the caption_* lint rules: see /embedded-captions.
      -->
      <style>
        #root {{
          position: absolute;
          inset: 0;
          pointer-events: none;
        }}
        .caption {{
          position: absolute;
          left: 10%;
          right: 10%;
          bottom: 14%;
          text-align: center;
          color: #ffffff;
          font-family: Inter, ui-sans-serif, system-ui, sans-serif;
          font-size: {caption_size}px;
          font-weight: 600;
          letter-spacing: -0.01em;
          text-shadow: 0 2px 18px rgba(0, 0, 0, 0.6);
        }}
      </style>

      <div id="root" data-composition-id="{cid}" data-width="{width}" data-height="{height}">
        <div class="caption clip" id="captions-first" data-start="0" data-duration="2" data-track-index="0">
          <span>[first caption]</span>
        </div>
      </div>

      <script>
        const tl = gsap.timeline({{ paused: true }});
        window.__timelines["{cid}"] = tl;
        tl.seek(0);
      </script>
    </template>
  </body>
</html>
"""

ROOT_FILE = """<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width={width}, height={height}" />
    <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>
    <style>
      * {{ margin: 0; padding: 0; box-sizing: border-box; }}
      html, body {{
        margin: 0;
        width: {width}px;
        height: {height}px;
        overflow: hidden;
        background: {background};
      }}
      #root {{
        width: 100%;
        height: 100%;
        position: relative;
        font-family: Inter, ui-sans-serif, system-ui, sans-serif;
      }}
    </style>
  </head>
  <body>
    <!--
      {title} — scaffolded from video-spec.json by create-video.

      purpose  {purpose}
      axes     {genre} · {pacing} · {visual} · {camera} · {editing} · {tone}
      frame    {width}x{height} ({aspect}) · {fps} fps · {duration:.1f}s · audio {audio}
      arrivals {arrivals} across {scenes} scenes

      The root holds timed hosts and nothing else. Nested markup here would
      collapse into one opaque row in Studio and could not be trimmed part by
      part — put structure in the scene file, not here.
    -->
    <div
      id="root"
      data-composition-id="main"
      data-start="0"
      data-duration="{duration}"
      data-width="{width}"
      data-height="{height}"
    >
{hosts}
    </div>
    <script>
      const tl = gsap.timeline({{ paused: true }});
      window.__timelines["main"] = tl;
      tl.seek(0);
    </script>
  </body>
</html>
"""

HOST = """      <div
        id="{cid}"
        data-composition-id="{cid}"
        data-composition-src="{src}"
        data-start="{start}"
        data-duration="{duration}"
        data-track-index="{track}"
        data-track-kind="{kind}"
        data-width="{width}"
        data-height="{height}"
      ></div>"""

FRAME_MD = """---
name: {title}
colors:
  background: "#0a0a0a"
  text: "#f4f4f5"
  accent: "#3b82f6"   # replace with the brand accent before authoring
typography:
  display: {display_font}
  body: Inter, ui-sans-serif, system-ui, sans-serif
  scale: 1.33
spacing:
  unit: 8px
  safe_action: 5%      # 90% of the frame — everything visible
  safe_title: 10%      # 80% of the frame — captions and key content
components:
  scene: compositions/scenes/*.html
  decoration: compositions/decorations/ambient.html
  caption: compositions/captions.html
---

# Frame — {title}

Visual style `{visual}` · tone `{tone}`. Frontmatter is the normative layer:
quote these tokens verbatim in every scene, and replace the placeholder accent
with the real brand value before authoring. Prose below is context, not values.

## The frame

{visual_note}. One subject per frame; {aspect} canvas at {width}x{height}.

## Motion register

Tone `{tone}` → `{ease}`. Pacing `{pacing}` → arrivals of
{shot_lo:.1f}–{shot_hi:.1f}s, transitions {tr_lo}–{tr_hi} ms. Camera `{camera}`:
{camera_note}.

## Do not

- Introduce a colour, weight, or radius that is not in the frontmatter.
- Let a scene hold its full window without the arrivals the spec budgets.
- Put captions outside the title-safe box.
"""


def slug(text: str) -> str:
    return re.sub(r"-+", "-", re.sub(r"[^a-z0-9]+", "-", text.lower())).strip("-") or "scene"


def build(spec: dict, project: Path, dry: bool) -> list[tuple[Path, str]]:
    errors: list[str] = []
    warnings: list[str] = []
    derived = validate(spec, errors, warnings)
    if errors:
        raise SystemExit("spec has errors — fix them before scaffolding:\n- " + "\n- ".join(errors))

    width, height = derived["canvas"]
    dims = derived["dims"]
    fps = derived["fps"]
    duration = derived["total"]
    tone = dims.get("tone", "calm")
    ease = EASE.get(tone, "power2.out")
    pacing_key = dims.get("pacing", "moderate")
    (shot_lo, shot_hi) = PACING[pacing_key][1]
    (tr_lo, tr_hi) = PACING[pacing_key][2]
    entrance = round(min(0.8, max(0.18, ((tr_lo + tr_hi) / 2) / 1000)), 2)

    files: list[tuple[Path, str]] = []
    hosts: list[str] = []

    # decoration host spans the film, on the lowest graphics track
    hosts.append(HOST.format(cid="decorations", src="compositions/decorations/ambient.html",
                             start=0, duration=round(duration, 3), track=0, kind="graphics",
                             width=width, height=height))
    files.append((project / "compositions/decorations/ambient.html",
                  DECORATION_FILE.format(cid="decorations", width=width, height=height,
                                         fade=min(2.0, duration * 0.15), ease=ease)))

    display_font = {"minimal": "Inter, ui-sans-serif, system-ui, sans-serif",
                    "editorial": "Georgia, ui-serif, serif",
                    "cinematic": "Inter, ui-sans-serif, system-ui, sans-serif"}.get(
        dims.get("visual_style"), "Inter, ui-sans-serif, system-ui, sans-serif")

    for scene in derived["plan"]:
        cid = f"scene-{scene['index']:02d}"
        fname = f"{scene['index']:02d}-{slug(scene['role'])}.html"
        src = f"compositions/scenes/{fname}"
        seconds = scene["seconds"]
        beats = max(1, scene["beats"])
        window = round(seconds / beats, 3)

        markup, tweens = [], []
        promise_dir = scene["promise"]["expect"] if scene["promise"] else None
        fade = round(entrance * 0.3, 3)
        for n in range(1, beats + 1):
            bid = f"{cid}-beat-{n}"
            t = round((n - 1) * window, 3)
            # A fromTo authored at a future position must not pre-render its from-state,
            # or a seek to t=0 inherits whichever fromTo was written last. lint flags it.
            hold = ", immediateRender: false" if t > 0 else ""
            markup.append(BEAT_MARKUP.format(
                bid=bid, n=n, track=n, start=round((n - 1) * window, 3),
                duration=round(window, 3),
                hint="content" if n == 1 else f"arrival {n} of {beats}"))
            if promise_dir in OFFSET:
                dx, dy = OFFSET[promise_dir]
                tweens.append(
                    f'        tl.fromTo("#{bid} > span", {{ opacity: 0 }}, '
                    f'{{ opacity: 1, duration: {fade}, ease: "linear"{hold} }}, {t});')
                tweens.append(
                    f'        tl.fromTo("#{bid} > span", {{ x: {dx}, y: {dy} }}, '
                    f'{{ x: 0, y: 0, duration: {entrance}, ease: "{ease}", '
                    f'immediateRender: false }}, {t});  '
                    f'// travel: {promise_dir} — opaque before it moves, so it can be measured')
            elif promise_dir == "in-place":
                tweens.append(
                    f'        tl.fromTo("#{bid} > span", {{ opacity: 0, scale: 0.94 }}, '
                    f'{{ opacity: 1, scale: 1, duration: {entrance}, ease: "{ease}"{hold} }}, {t});  '
                    f'// promised in-place: it changes without travelling')
            else:
                tweens.append(
                    f'        tl.fromTo("#{bid} > span", {{ opacity: 0, y: 28 }}, '
                    f'{{ opacity: 1, y: 0, duration: {entrance}, ease: "{ease}"{hold} }}, {t});')

        files.append((project / src, SCENE_TEMPLATE.format(
            index=scene["index"], role=scene["role"], start=f"{scene['start']:.1f}s",
            end=f"{scene['end']:.1f}s", seconds=seconds, intent=scene["intent"] or "—",
            content=scene["content"] or "[slot]", beats=beats, pacing=pacing_key,
            shot_lo=shot_lo, shot_hi=shot_hi,
            blueprints=", ".join(scene["blueprints"]) or "compose from rules-index.md",
            motion=(f"{scene['promise']['expect']} — {scene['promise']['what']}"
                    if scene["promise"] else "unspecified"),
            ease=ease, tone=tone,
            blueprint_doc="blueprints/<id>.md " if scene["blueprints"] else "",
            cid=cid, width=width, height=height,
            font_size=max(56, int(height * 0.075)),
            font_weight=800 if dims.get("pacing") in ("fast", "very_fast") else 700,
            beats_markup="\n".join(markup), beats_tweens="\n".join(tweens))))

        hosts.append(HOST.format(cid=cid, src=src, start=round(scene["start"], 3),
                                 duration=round(seconds, 3), track=scene["index"],
                                 kind="graphics", width=width, height=height))

    # one caption track, above every scene host
    hosts.append(HOST.format(cid="captions", src="compositions/captions.html", start=0,
                             duration=round(duration, 3), track=len(derived["plan"]) + 1,
                             kind="captions", width=width, height=height))
    files.append((project / "compositions/captions.html",
                  CAPTIONS_FILE.format(cid="captions", width=width, height=height,
                                       caption_size=max(34, int(height * 0.042)))))

    files.append((project / "index.html", ROOT_FILE.format(
        width=width, height=height, duration=round(duration, 3),
        title=spec.get("title", "Untitled"), purpose=spec.get("purpose", "—"),
        genre=dims.get("genre"), pacing=pacing_key, visual=dims.get("visual_style"),
        camera=dims.get("camera_style"), editing=dims.get("editing_style"), tone=tone,
        aspect=derived["aspect"], fps=fps, background="#0a0a0a", audio=spec.get("audio", "none"),
        arrivals=sum(s["beats"] for s in derived["plan"]), scenes=len(derived["plan"]),
        hosts="\n".join(hosts))))

    files.append((project / "frame.md", FRAME_MD.format(
        title=spec.get("title", "Untitled"), visual=dims.get("visual_style"), tone=tone,
        display_font=display_font, visual_note="—", camera=dims.get("camera_style"),
        camera_note=derived["camera"]["note"], pacing=pacing_key, shot_lo=shot_lo,
        shot_hi=shot_hi, tr_lo=tr_lo, tr_hi=tr_hi, ease=ease, aspect=derived["aspect"],
        width=width, height=height)))

    files.append((project / ".gitignore", GITIGNORE))
    for name in ASSET_DIRS:
        files.append((project / "assets" / name / ".gitkeep", ""))
    return files


def main() -> int:
    ap = argparse.ArgumentParser(prog="scaffold", description=__doc__.splitlines()[0])
    ap.add_argument("spec", type=Path, help="video-spec.json")
    ap.add_argument("--project", type=Path, required=True, help="hyperframes project directory")
    ap.add_argument("--dry-run", action="store_true", help="list what would be written")
    ap.add_argument("--force", action="store_true", help="overwrite existing generated files")
    args = ap.parse_args()

    path = args.spec.expanduser().resolve()
    if not path.is_file():
        raise SystemExit(f"spec not found: {path}")
    project = args.project.expanduser().resolve()
    if not project.is_dir():
        raise SystemExit(f"{project} does not exist — run `npx hyperframes init {project.name}` first")
    if not (project / "hyperframes.json").is_file():
        raise SystemExit(f"{project} has no hyperframes.json — that is init's file, not this script's; "
                         f"run `npx hyperframes init` in it first")

    spec = json.loads(path.read_text())
    files = build(spec, project, args.dry_run)

    written, skipped = [], []
    for target, content in files:
        if target.exists() and not args.force:
            skipped.append(target)
            continue
        if args.dry_run:
            print(f"would write {target.relative_to(project)}")
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)
        written.append(target)

    if args.dry_run:
        return 0
    print(f"# scaffolded {project.name}")
    print()
    for target in written:
        print(f"  wrote {target.relative_to(project)}")
    for target in skipped:
        print(f"  kept  {target.relative_to(project)} (exists; --force to overwrite)")
    print()
    print("Next:")
    print("  npx hyperframes lint .          # 0 errors before authoring")
    print("  npx hyperframes check . --json  # runtime, layout, motion, contrast")
    print("  python3 scripts/spec.py video-spec.json   # the arrival budget to fill in")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
